import GeometricMeasureTheory.Varifold
import Mathlib.Geometry.Manifold.IsManifold.Basic
import Mathlib.Geometry.Manifold.MFDeriv.Basic
import Mathlib.MeasureTheory.Integral.Bochner.Basic

/-!
# AltRegularity.GMT.SecondVariation

Second variation of a varifold along a normal deformation.

For a smooth varifold supported on a hypersurface $\Sigma$ with second
fundamental form $A$, the second variation along a scalar normal
deformation $\varphi$ has the classical Jacobi form
$$\delta^2 V(\varphi, \varphi)
  = \int_\Sigma \big(|\nabla \varphi|^2 - (|A|^2 + \mathrm{Ric}(\nu, \nu))
                 \varphi^2\big)\, d\mathcal{H}^n.$$

This is the GMT primitive used to express:
  * Stability — paper §4 Definition 4.1 (S2)
    (`AltRegularity.Regularity.AlphaStructural`)
  * Local stability of varifolds — paper §7.1
    (`AltRegularity.Regularity.StabilityVerification`)

## Definition style

`secondVariation` is grounded with the **kinetic term real, curvature
term placeholder**: the kinetic $|\nabla \varphi|^2$ uses the same
chart-pullback + `fderiv` pattern as `firstVariation`, while the
curvature contribution $|A|^2 + \mathrm{Ric}(\nu, \nu)$ is set to 0
(documented gap). Chain proofs treat `IsStable V` (which references
`secondVariation`) as a black-box hypothesis and never inspect the
specific value, so the placeholder does not propagate into chain-proof
correctness. Future Varifold-with-normal-field + Mathlib-Ricci
refinements would close the curvature gap fully.
-/

open scoped ContDiff Manifold

namespace GeometricMeasureTheory

variable {M : Type*} [MetricSpace M] [MeasurableSpace M] [BorelSpace M] [MeasureTheory.MeasureSpace M]

namespace Varifold

/-- **Squared norm of the gradient on $M$** at $x$, computed in the
chart at $x$ via `fderiv` on the chart-pulled-back scalar function.

For a flat ambient ($M$ open in a normed space), this equals the
standard Euclidean $|\nabla \varphi|^2$. For curved Riemannian ambient,
it gives the operator-norm squared of the chart-local Fréchet
derivative; in an isometric chart at $x$ (e.g., normal coordinates),
this matches the Riemannian gradient norm
$|\nabla^g \varphi|^2_g = g^{ij} \partial_i \varphi\, \partial_j \varphi$.
The general Riemannian form differs by metric-tensor correction terms;
Mathlib does not yet expose a `gradient` operator on charted spaces.

**Ground truth**: standard differential calculus; flat-space form is
unambiguous, manifold-curved form is a chart-local approximation.

**Used by**: `secondVariation`. -/
noncomputable def gradientNormSqM
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    {H : Type*} [TopologicalSpace H]
    (I : ModelWithCorners ℝ E H)
    [ChartedSpace H M] [IsManifold I ∞ M]
    (φ : M → ℝ) (x : M) : ℝ :=
  ‖fderiv ℝ (φ ∘ (extChartAt I x).symm) ((extChartAt I x) x)‖ ^ 2

/-- The **second variation** of $V$ along a smooth scalar normal
deformation $\varphi$, $\delta^2 V(\varphi, \varphi) \in \mathbb{R}$.

This is the second derivative of the total mass under the one-parameter
family of varifolds generated by infinitesimal normal deformation
$\varphi$. For a smooth codim-1 varifold supported on a hypersurface
$\Sigma$ with second fundamental form $A$ in a Riemannian ambient $M$:
$$\delta^2 V(\varphi, \varphi)
  = \int_\Sigma \big(|\nabla \varphi|^2 - (|A|^2 + \mathrm{Ric}(\nu, \nu))
                 \varphi^2\big)\, d\|V\|.$$

**Current grounding** (Layer B C-3, post-firstVariation precedent):
the kinetic term $|\nabla \varphi|^2$ is real (`gradientNormSqM`,
chart-pullback of `fderiv ℝ φ`); the curvature term
$|A|^2 + \mathrm{Ric}(\nu, \nu)$ is set to **0** (placeholder).

**Curvature placeholder gap**:
  * **Second fundamental form $|A|^2$**: requires the normal bundle of
    $\mathrm{spt}\, V$ inside $M$ + the Riemannian connection. The
    mass-only `Varifold` carries no normal-field data; promoting
    requires `Varifold` refinement.
  * **Ambient Ricci $\mathrm{Ric}$**: Mathlib's
    `Geometry/Manifold/Riemannian/` has the metric tensor but no
    `Ricci` operator at this level.

Chain proofs use `IsStable V` (`∀ φ, 0 ≤ secondVariation V φ`) as a
black-box hypothesis. They never inspect the specific value of
`secondVariation V φ`, so the curvature placeholder does not propagate
into chain-proof correctness. The `firstVariation` precedent (commit
1acef9f) shows the same pattern: kinetic ambient form grounded with
documented codim-1 caveat, full GMT form deferred to future Varifold
refinement.

**Ground truth**: Simon 1983 §49 (Jacobi field setup, second variation
formula for stationary integral varifolds); Schoen–Simon 1981 §1
(stable hypersurfaces); Wickramasekera 2014 §2 (codim-1 form).

**Used by**: `Varifold.IsStable` (`Regularity/AlphaStructural.lean`),
`Varifold.LocallyStable` (`Regularity/StabilityVerification.lean`). -/
noncomputable def secondVariation
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    {H : Type*} [TopologicalSpace H]
    (I : ModelWithCorners ℝ E H)
    [ChartedSpace H M] [IsManifold I ∞ M]
    (V : Varifold M) (φ : M → ℝ) : ℝ :=
  ∫ x, gradientNormSqM I φ x ∂V.massMeasure
  -- Curvature term `(|A|²(x) + Ric(ν, ν)(x)) * φ x ^ 2` set to 0
  -- (placeholder); see docstring above.

end Varifold

end GeometricMeasureTheory
